### ISSUE TITLE
what is the status of this project?

### ISSUE THREAD

**Issue by notjames** [robertlestak/cert-manager-sync#3]
We're considering using this operator and we're having an issue with the operator not syncing the private key to ACM. There's one issue in this queue which seems to have never been touched since 2021. Thoughts?

**Comment by wwwlde** [comment]
The code is running smoothly; it's alive and well.

**Comment by robertlestak** [comment]
sorry for the delay, I can confirm it's still active, just haven't gotten around to making any changes recently since it does "just work" (at least in my environments, and from what I hear, others' as well!).

I did just push some changes which implement a cleaner interface with the goal of making it more extendable to other providers in the future.

if you're having issues with ACM, make sure the operator has proper auth to ACM. If running in EKS, this can be done with [IRSA](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html), if elsewhere you'll need to create an IAM user `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, store those as a k8s secret, and then export them to the env with `envFrom.secretRef` in the deployment manifest.

**Comment by notjames** [comment]
Thanks @robertlestak  --
We ended up coming up with a solution.
